"""R42-Census — Step A: real-text exception-density census (inference-only, no training).

Question (codex-converged 2026-07-08, qa/codex/2026-07-08.21.29.23.md): what fraction of NATURAL text
behaves like the off-manifold exception tail (high frozen-base bits/token) that R40-s3/R41 showed is
where replay budget must go? All prior positives sit on a CONSTRUCTED 50/50 squad+synth mixture — the
density was manufactured. This census measures the real bits/token distribution over atomic-fact
probes drawn from real text. Deliverable IS the number: O(#exceptions)/O(#facts) with CIs, as a curve
over thresholds (no pretending there is a natural binary class if the distribution is unimodal).

codex: the 3B probe generator is Step A's MAIN failure mode -> the census is a probe-QUALITY AUDIT,
not a histogram job. Gates: 3B entailment faithfulness (calibrated against human SQuAD probes),
extractive-span precheck, dedup clustering, bits-vs-answer-length/type confound table, paraphrase
stability on a subset, passage-level bootstrap CIs (probes within a chapter are correlated).

Domains:
  squad_human — SQuAD dev passages with their HUMAN-authored QAs (generation-free anchor; also
                calibrates the 3B faithfulness verifier: if it rejects many human probes, the
                verifier — not the probes — is unreliable).
  wiki_gen    — wikimedia/wikipedia articles (3 stream offsets: dump head is popularity-biased),
                atomic probes generated by the 3B instruct model.
  news_gen    — cnn_dailymail articles, generated probes (off-wiki real-text domain).

Also: two-hop paired-probe canary (codex #2 metadata seed for the parked composition question) —
non-gating, reported separately. Anchors from R40-s3 for reference: screened-squad mean bits/token
~4.45 (on-manifold), synth ~11.37 (off-manifold). Model: Qwen2.5-0.5B base; 3B instruct for probes.
"""
import os, json, re, random, collections, time
import torch
from s3.wikibridge import normalize, em, QT, RT, gen, qa_answer_bits, load_model, tok, device
from transformers import AutoModelForCausalLM, AutoTokenizer

SEED = int(os.environ.get("CN_SEED", 0))
N_SQ = int(os.environ.get("CN_SQUAD_N", 40))       # passages per domain
N_WIKI = int(os.environ.get("CN_WIKI_N", 42))      # divisible by 3 offsets
N_NEWS = int(os.environ.get("CN_NEWS_N", 40))
PROBES_PER = int(os.environ.get("CN_PROBES_PER", 6))
N_PARA2 = int(os.environ.get("CN_PARA2", 120))     # subset size for 2nd-paraphrase stability audit
N_TWOHOP = int(os.environ.get("CN_TWOHOP", 20))    # passages per domain for the two-hop canary
OUT = os.environ.get("CN_OUT", "census_result.json")
PARA_NAME = os.environ.get("WB_PARA_MODEL", "Qwen/Qwen2.5-3B-Instruct")
TAUS = [float(x) for x in os.environ.get("CN_TAUS", "6,8,10").split(",")]
CATS = {"entity", "relation", "number", "date", "causal", "procedural", "claim"}

# ------------------------- 3B instruct wrapper (loaded ONCE; probes + judge + paraphrase) ---------
class Instruct:
    def __init__(self, name=PARA_NAME):
        self.m = AutoModelForCausalLM.from_pretrained(name, dtype=torch.bfloat16).to(device).eval()
        self.t = AutoTokenizer.from_pretrained(name)
        if self.t.pad_token is None:
            self.t.pad_token = self.t.eos_token
        self.t.padding_side = "left"

    @torch.no_grad()
    def chat(self, pairs, max_new=64, bs=8):        # pairs: list of (system, user) -> list of str
        outs = []
        for i in range(0, len(pairs), bs):
            chunk = pairs[i:i + bs]
            texts = [self.t.apply_chat_template(
                [{"role": "system", "content": s}, {"role": "user", "content": u}],
                tokenize=False, add_generation_prompt=True) for s, u in chunk]
            e = self.t(texts, return_tensors="pt", padding=True, truncation=True, max_length=1600).to(device)
            g = self.m.generate(**e, max_new_tokens=max_new, do_sample=False, pad_token_id=self.t.pad_token_id)
            for j in range(g.shape[0]):
                outs.append(self.t.decode(g[j, e["input_ids"].shape[1]:], skip_special_tokens=True).strip())
        return outs

    def free(self):
        del self.m; torch.cuda.empty_cache()

# NOTE first pod run: the 3B copies "<TAB>" LITERALLY instead of emitting a tab, and omits question
# marks without an example -> 0 parsed probes. Fix: pipe separator + one-shot example + explicit "?".
PSYS = ("You extract atomic factual question-answer pairs from a passage. Rules: each answer MUST be an "
        "exact short span copied verbatim from the passage (at most 6 words); each question must be fully "
        "answerable from the passage alone, must test exactly ONE fact, must end with a question mark, and "
        "must not contain the answer. Label each pair with one category word: entity, relation, number, "
        "date, causal, procedural, or claim. Output ONLY lines in this exact format (one pair per line):\n"
        "category | question | answer\n"
        "Example:\ndate | When did the treaty enter into force? | 1854")
PUSR = "Passage:\n{c}\n\nExtract up to {k} pairs."
FSYS = ("Judge whether the passage supports the given answer to the question. Minor wording differences "
        "are acceptable. Reply with exactly one word: yes or no.")
# Step-B screen (codex 2026-07-08): deictic probes ("What is the name of the dog?") are not globally
# addressable closed-book facts; training them inflates the exception tail with in-principle-unanswerable
# items. Screen is a property of the QUESTION alone (no passage shown to the judge).
SSYS = ("Judge whether the question identifies its subject specifically enough that a person who knows "
        "the relevant facts could answer it without any additional context. Reply with exactly one word: "
        "yes or no.")
FUSR = "Passage:\n{c}\n\nQuestion: {q}\nProposed answer: {a}\n\nDoes the passage state this? Answer yes or no."
RSYS = ("Reword the question so it has the SAME meaning and the SAME answer but DIFFERENT wording. "
        "Output only the reworded question, nothing else.")
# 2nd paraphrase channel: decoding is GREEDY, so the same (system,user) pair would reproduce paraphrase #1
# verbatim. A differently-worded instruction gives an independent deterministic channel for the stability audit.
RSYS2 = ("Rephrase the question in your own words, keeping the same meaning and the same answer. "
         "Output only the rephrased question, nothing else.")
TSYS = ("Write ONE question that can only be answered by combining TWO different facts stated in the "
        "passage. The answer must be an exact short span (at most 6 words) copied from the passage, and "
        "the question must end with a question mark. Output exactly one line in this format:\n"
        "question | answer")

# ------------------------- domains -------------------------
def _cut(txt, n=1400):                              # passage = head of article, cut at sentence boundary
    s = txt[:n]
    return s[:s.rfind(".") + 1] or s

def load_squad_human(rng):
    from datasets import load_dataset
    ds = load_dataset("rajpurkar/squad", split="validation")
    by_ctx = collections.defaultdict(list)
    for r in ds:
        by_ctx[r["context"]].append(r)
    ctxs = sorted(by_ctx); rng.shuffle(ctxs)
    out = []
    for c in ctxs:
        qas, seen = [], set()
        for r in by_ctx[c]:
            golds = list(dict.fromkeys(r["answers"]["text"]))
            if not golds or r["question"] in seen:
                continue
            if not (1 <= len(tok(golds[0], add_special_tokens=False).input_ids) <= 8):
                continue
            seen.add(r["question"])
            qas.append(dict(question=r["question"], answers=golds, category="human"))
        if len(qas) >= 3:
            out.append(dict(pid=f"squad:{len(out)}", title=by_ctx[c][0]["title"], context=c,
                            qas=qas[:PROBES_PER]))
        if len(out) >= N_SQ:
            break
    return out

def load_wiki(rng):
    # dump order ~ page-id ascending -> head is old/popular pages (pretraining-saturated). Sample THREE
    # stream offsets so the census is not just the famous head; report is per-domain pooled anyway.
    from datasets import load_dataset
    ds = load_dataset("wikimedia/wikipedia", "20231101.en", split="train", streaming=True)
    offsets = [2000, 60000, 200000]
    want = [N_WIKI - 2 * (N_WIKI // 3), N_WIKI // 3, N_WIKI // 3]
    out, oi, taken = [], 0, 0
    for i, r in enumerate(ds):
        if oi >= len(offsets):
            break
        if i < offsets[oi]:
            continue
        txt = r["text"]
        if len(txt) >= 1500:
            out.append(dict(pid=f"wiki:{len(out)}", title=r["title"], context=_cut(txt)))
            taken += 1
        if taken >= want[oi]:
            oi += 1; taken = 0
    return out

def load_news(rng):
    from datasets import load_dataset
    ds = load_dataset("abisee/cnn_dailymail", "3.0.0", split="test")   # hub now requires namespace/name
    idx = list(range(len(ds))); rng.shuffle(idx)
    out = []
    for i in idx:
        a = ds[i]["article"]
        if len(a) < 1500:
            continue
        out.append(dict(pid=f"news:{len(out)}", title=f"cnn_{i}", context=_cut(a)))
        if len(out) >= N_NEWS:
            break
    return out

# ------------------------- generated probes (wiki/news) -------------------------
def gen_probes(inst, passages):
    outs = inst.chat([(PSYS, PUSR.format(c=p["context"], k=PROBES_PER)) for p in passages], max_new=340, bs=8)
    kept = []
    for p, o in zip(passages, outs):
        qas, seen = [], set()
        for line in o.split("\n"):
            parts = [x.strip() for x in line.split("|")]
            if len(parts) != 3:                                # tolerate tab / literal "<TAB>" variants
                parts = [x.strip() for x in re.split(r"\t|<TAB>|<Tab>|<tab>", line)]
            if len(parts) != 3:
                continue
            cat, q, a = parts
            cat = cat.lower().strip(" :")
            if cat not in CATS or not q.endswith("?") or not a:
                continue
            if a.lower() not in p["context"].lower():          # extractive-span precheck (faithfulness #1)
                continue
            if not (1 <= len(tok(a, add_special_tokens=False).input_ids) <= 8):
                continue
            na = normalize(a)
            if not na or na in normalize(q):                   # question leaks the answer
                continue
            if q in seen:
                continue
            seen.add(q)
            qas.append(dict(question=q, answers=[a], category=cat))
        p["qas"] = qas[:PROBES_PER]
        if len(p["qas"]) >= 2:
            kept.append(p)
    return kept

def ans_kind(a):                                    # coarse heuristic type, uniform across ALL domains
    if re.search(r"\d", a):
        return "number/date"
    ws = a.split()
    if ws and all(w[:1].isupper() for w in ws if w[:1].isalpha()):
        return "proper"
    return "other"

# ------------------------- summary stats -------------------------
def _q(sorted_v, f):
    return sorted_v[min(len(sorted_v) - 1, int(f * len(sorted_v)))] if sorted_v else None

def tail_stats(rows, rng, label):
    """density curve over bits/token thresholds + passage bootstrap CI; rows = census rows (one domain)."""
    bpt = sorted(r["bpt_para"] for r in rows)
    if not bpt:
        return dict(label=label, n=0)
    groups = collections.defaultdict(list)
    for r in rows:
        groups[r["pid"]].append(r["bpt_para"])
    pids = list(groups)
    def frac(pool, tau):
        return sum(1 for b in pool if b > tau) / max(len(pool), 1)
    tails = {}
    for tau in TAUS:
        fr = []
        for _ in range(1000):                       # passage-level bootstrap (probes within chapter correlate)
            pool = [b for pid in (rng.choice(pids) for _ in pids) for b in groups[pid]]
            fr.append(frac(pool, tau))
        fr.sort()
        tails[f"tau{tau:g}"] = dict(frac=round(frac(bpt, tau), 3),
                                    ci95=[round(fr[25], 3), round(fr[974], 3)])
    curve = {f"{t:g}": round(frac(bpt, t), 3) for t in range(2, 17, 2)}
    return dict(label=label, n=len(bpt), n_passages=len(pids),
                mean=round(sum(bpt) / len(bpt), 2), median=round(_q(bpt, 0.5), 2),
                deciles=[round(_q(bpt, f / 10), 2) for f in range(1, 10)],
                tails=tails, curve=curve)

def main():
    t0 = time.time()
    rng = random.Random(4200 + SEED)
    print(f"CENSUS (base={os.environ.get('WB_MODEL','Qwen/Qwen2.5-0.5B')}, probe_gen={PARA_NAME}, {device}) "
          f"squad={N_SQ} wiki={N_WIKI} news={N_NEWS} probes/passage<={PROBES_PER} taus={TAUS}", flush=True)
    base = load_model()
    inst = Instruct()                               # 0.5B + 3B coexist on 24GB

    # ---- passages + probes per domain ----
    dom_pass = {"squad_human": load_squad_human(rng)}
    print(f"  squad_human: {len(dom_pass['squad_human'])} passages (human QAs)", flush=True)
    for name, loader in (("wiki_gen", load_wiki), ("news_gen", load_news)):
        ps = loader(rng)
        ps = gen_probes(inst, ps)
        dom_pass[name] = ps
        print(f"  {name}: {len(ps)} passages with >=2 parsed probes "
              f"({sum(len(p['qas']) for p in ps)} probes)", flush=True)

    probes = []                                     # flat rows
    for dom, ps in dom_pass.items():
        for p in ps:
            for j, q in enumerate(p["qas"]):
                q["qid"] = f"{dom}:{p['pid']}:{j}"; q["domain"] = dom; q["pid"] = p["pid"]
                q["context"] = p["context"]
                probes.append(q)
    print(f"  total probes: {len(probes)}", flush=True)

    # ---- 3B faithfulness judge on ALL probes (squad_human rows CALIBRATE the judge itself) ----
    fv = inst.chat([(FSYS, FUSR.format(c=q["context"], q=q["question"], a=q["answers"][0]))
                    for q in probes], max_new=4, bs=16)
    for q, v in zip(probes, fv):
        q["faithful"] = int(v.strip().lower().startswith("yes"))
    for dom in dom_pass:
        sub = [q for q in probes if q["domain"] == dom]
        fr = sum(q["faithful"] for q in sub) / max(len(sub), 1)
        print(f"  faithfulness[{dom}] = {fr:.3f} ({sum(q['faithful'] for q in sub)}/{len(sub)})"
              + ("  <- judge CALIBRATION (human probes)" if dom == "squad_human" else ""), flush=True)

    # ---- self-containedness screen: pre/post densities both reported; Step B trains on yes-rows only ----
    sv = inst.chat([(SSYS, f"Question: {q['question']}") for q in probes], max_new=4, bs=16)
    for q, v in zip(probes, sv):
        q["self_contained"] = int(v.strip().lower().startswith("yes"))
    for dom in dom_pass:
        sub = [q for q in probes if q["domain"] == dom]
        print(f"  self_contained[{dom}] = {sum(q['self_contained'] for q in sub)}/{len(sub)}", flush=True)

    # ---- paraphrases: 1 for all, a 2nd for a stability subset ----
    paras = inst.chat([(RSYS, q["question"]) for q in probes], max_new=40, bs=16)
    for q, p in zip(probes, paras):
        q["eval_question"] = (p.split("\n")[0].strip() or q["question"])
    sub_idx = rng.sample(range(len(probes)), min(N_PARA2, len(probes)))
    paras2 = inst.chat([(RSYS2, probes[i]["question"]) for i in sub_idx], max_new=40, bs=16)
    for i, p in zip(sub_idx, paras2):
        probes[i]["eval_question2"] = (p.split("\n")[0].strip() or probes[i]["question"])

    # ---- two-hop paired-probe canary (non-gating; seed data for the parked composition question) ----
    twohop = []
    th_pass = [p for dom in dom_pass for p in dom_pass[dom][:N_TWOHOP]]
    for p, o in zip(th_pass, inst.chat([(TSYS, f"Passage:\n{p['context']}") for p in th_pass], max_new=64, bs=8)):
        parts = [x.strip() for x in re.split(r"\||\t|<TAB>|<Tab>", o.split("\n")[0])]
        if len(parts) == 2 and parts[1] and parts[1].lower() in p["context"].lower() \
           and 1 <= len(tok(parts[1], add_special_tokens=False).input_ids) <= 8:
            twohop.append(dict(question=parts[0], answers=[parts[1]], context=p["context"],
                               pid=p["pid"], domain=p["pid"].split(":")[0]))
    fv2 = inst.chat([(FSYS, FUSR.format(c=q["context"], q=q["question"], a=q["answers"][0]))
                     for q in twohop], max_new=4, bs=16)
    for q, v in zip(twohop, fv2):
        q["faithful"] = int(v.strip().lower().startswith("yes"))
    print(f"  two-hop canary: {len(twohop)} parsed, faithful={sum(q['faithful'] for q in twohop)}", flush=True)
    inst.free()

    # ---- frozen-base scoring: closed-book EM + bits/token (orig & para) + gold-passage RAG EM ----
    def base_score(qs):
        go = gen(base, [QT.format(q=q["question"]) for q in qs])
        gp = gen(base, [QT.format(q=q.get("eval_question", q["question"])) for q in qs])
        gr = gen(base, [RT.format(c=q["context"], q=q["question"]) for q in qs])
        bo = qa_answer_bits(base, qs, "question")
        bp = qa_answer_bits(base, [dict(q, question=q.get("eval_question", q["question"])) for q in qs], "question")
        for k, q in enumerate(qs):
            q["base_em_orig"] = em(go[k], q["answers"]); q["base_em_para"] = em(gp[k], q["answers"])
            q["rag_em_orig"] = em(gr[k], q["answers"])
            q["bits_orig"], q["ans_ntok"] = bo[k]
            q["bits_para"] = bp[k][0]
            q["bpt_orig"] = round(q["bits_orig"] / max(q["ans_ntok"], 1), 3)
            q["bpt_para"] = round(q["bits_para"] / max(q["ans_ntok"], 1), 3)
    for i in range(0, len(probes), 200):
        base_score(probes[i:i + 200]); print(f"  scored {min(i+200,len(probes))}/{len(probes)}", flush=True)
    if twohop:
        base_score(twohop)
    # paraphrase-stability subset: bits/token under the 2nd paraphrase
    sub = [q for q in probes if "eval_question2" in q]
    if sub:
        b2 = qa_answer_bits(base, [dict(q, question=q["eval_question2"]) for q in sub], "question")
        for q, (bb, _) in zip(sub, b2):
            q["bpt_para2"] = round(bb / max(q["ans_ntok"], 1), 3)

    # ---- dedup clustering: same passage + same normalized answer = near-dup fact ----
    seen_cl = {}
    for q in probes:
        cl = f"{q['pid']}::{normalize(q['answers'][0])}"
        q["cluster"] = cl; q["dup"] = int(cl in seen_cl); seen_cl.setdefault(cl, q["qid"])
        q["kind"] = ans_kind(q["answers"][0])

    # ---- rows out (jsonl; context stored once per passage in the summary json) ----
    with open(OUT.replace(".json", ".jsonl"), "w") as f:
        for q in probes:
            f.write(json.dumps({k: v for k, v in q.items() if k != "context"}) + "\n")
        for q in twohop:
            f.write(json.dumps(dict({k: v for k, v in q.items() if k != "context"}, probe="twohop")) + "\n")

    # ---- summary: density curves (quality-gated) + confound strata + stability ----
    summ = {}
    for dom in dom_pass:
        rows = [q for q in probes if q["domain"] == dom]
        ok = [q for q in rows if not q["dup"] and (q["faithful"] or dom == "squad_human")]
        need = [q for q in ok if q["base_em_para"] == 0]       # items that actually NEED writing
        ok_sc = [q for q in ok if q["self_contained"]]         # Step-B planning subset (post-screen)
        summ[dom] = dict(
            n_raw=len(rows), n_gated=len(ok), n_need_write=len(need), n_sc=len(ok_sc),
            sc_rate=round(sum(q["self_contained"] for q in rows) / max(len(rows), 1), 3),
            all_sc=tail_stats(ok_sc, rng, f"{dom}/gated+sc"),
            faith_rate=round(sum(q["faithful"] for q in rows) / max(len(rows), 1), 3),
            dup_rate=round(sum(q["dup"] for q in rows) / max(len(rows), 1), 3),
            rag05_em=round(sum(q["rag_em_orig"] for q in ok) / max(len(ok), 1), 3),
            base_em_orig=round(sum(q["base_em_orig"] for q in ok) / max(len(ok), 1), 3),
            base_em_para=round(sum(q["base_em_para"] for q in ok) / max(len(ok), 1), 3),
            all=tail_stats(ok, rng, f"{dom}/gated"),
            need_write=tail_stats(need, rng, f"{dom}/need-write"),
            strat_kind={k: tail_stats([q for q in ok if q["kind"] == k], rng, k)
                        for k in ("number/date", "proper", "other")},
            strat_len={b: tail_stats([q for q in ok if lo <= q["ans_ntok"] <= hi], rng, b)
                       for b, lo, hi in (("1-2", 1, 2), ("3-4", 3, 4), ("5+", 5, 99))},
        )
        cat_ct = collections.Counter(q["category"] for q in ok)
        summ[dom]["categories"] = dict(cat_ct)
    stab = [q for q in probes if "bpt_para2" in q]
    if stab:
        d = [abs(q["bpt_para"] - q["bpt_para2"]) for q in stab]
        m1 = sum(q["bpt_para"] for q in stab) / len(stab); m2 = sum(q["bpt_para2"] for q in stab) / len(stab)
        s1 = (sum((q["bpt_para"] - m1) ** 2 for q in stab) / len(stab)) ** 0.5 or 1.0
        s2 = (sum((q["bpt_para2"] - m2) ** 2 for q in stab) / len(stab)) ** 0.5 or 1.0
        corr = sum((q["bpt_para"] - m1) * (q["bpt_para2"] - m2) for q in stab) / (len(stab) * s1 * s2)
        summ["paraphrase_stability"] = dict(n=len(stab), mean_abs_diff=round(sum(d) / len(d), 3),
                                            corr=round(corr, 3))
    if twohop:
        okt = [q for q in twohop if q["faithful"]]
        summ["twohop_canary"] = dict(n=len(twohop), n_faithful=len(okt),
                                     stats=tail_stats(okt, rng, "twohop") if okt else None,
                                     rag05_em=round(sum(q["rag_em_orig"] for q in okt) / max(len(okt), 1), 3))
    cfg = dict(seed=SEED, squad_n=N_SQ, wiki_n=N_WIKI, news_n=N_NEWS, probes_per=PROBES_PER,
               taus=TAUS, para2=N_PARA2, twohop=N_TWOHOP,
               anchors_r40=dict(squad_screened_mean_bpt=4.45, synth_mean_bpt=11.37))
    json.dump(dict(config=cfg, summary=summ,
                   passages={p["pid"]: dict(title=p["title"], domain=dom, context=p["context"])
                             for dom, ps in dom_pass.items() for p in ps}),
              open(OUT, "w"), indent=1)
    print("SUMMARY " + json.dumps({d: dict(n=summ[d]["n_gated"], n_sc=summ[d]["n_sc"], faith=summ[d]["faith_rate"],
                                           sc=summ[d]["sc_rate"], mean_bpt=summ[d]["all"].get("mean"),
                                           tails={k: v["frac"] for k, v in summ[d]["all"].get("tails", {}).items()},
                                           sc_tails={k: v["frac"] for k, v in summ[d]["all_sc"].get("tails", {}).items()})
                                   for d in dom_pass}), flush=True)
    print(f"[done] wall={time.time() - t0:.0f}s", flush=True)

if __name__ == "__main__":
    main()
